---
name: ci

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - master
      - dev
      - staging
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

concurrency:
  group:
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUST_TEST_THREADS: 1
  RUSTDOCFLAGS: -D warnings
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10
  RUST_LOG: info

defaults:
  run:
    shell: bash

jobs:
  test-versions:
    name: Test Suite on ${{ matrix.rust }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # if you have an MSRV, you can of course include it here too.
        rust: [stable, beta, nightly]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@7d3610100de4da85ebb79cf22ad4c19bb1f68e12
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: dtolnay/rust-toolchain@f7003eed5ea1f2175ea1d670748f9c21af4f5d9e
        with:
          toolchain: ${{ matrix.rust }}
          components: rust-src
      - uses: taiki-e/install-action@74efbe3ca41988b1c402800fbd3a72c98c9d8eaa
        with:
          tool: cargo-hack
      - uses: taiki-e/install-action@74efbe3ca41988b1c402800fbd3a72c98c9d8eaa
        with:
          tool: nextest
      - uses: Swatinem/rust-cache@90429b3dea365e9a1b0cb82d7f98aabf3089dc63
        with:
          key: ${{ matrix.rust }}
      - run: cargo hack nextest run --no-capture --each-feature --profile ci
        timeout-minutes: 15

  msrv:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@7d3610100de4da85ebb79cf22ad4c19bb1f68e12
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          persist-credentials: false
      - uses: taiki-e/install-action@74efbe3ca41988b1c402800fbd3a72c98c9d8eaa
        with:
          tool: cargo-hack
      - run:
          cargo hack build -vvv --workspace --feature-powerset --optional-deps
          --ignore-private --no-dev-deps --version-range ..

  tidy:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@7d3610100de4da85ebb79cf22ad4c19bb1f68e12
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: dtolnay/rust-toolchain@f7003eed5ea1f2175ea1d670748f9c21af4f5d9e
        with:
          toolchain: nightly
          components: clippy,rustfmt
      - uses: taiki-e/install-action@74efbe3ca41988b1c402800fbd3a72c98c9d8eaa
        with:
          tool: cargo-hack
      - uses: taiki-e/install-action@74efbe3ca41988b1c402800fbd3a72c98c9d8eaa
        with:
          tool: cargo-minimal-versions
      - run: cargo fmt --all --check
        if: always()
      - run: cargo clippy --workspace --all-targets
        if: always()
        #@todo we'll have to integrate websockets into shit eventually.
      - run: cargo minimal-versions build --workspace --ignore-private
        if: always()

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@7d3610100de4da85ebb79cf22ad4c19bb1f68e12
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@f7003eed5ea1f2175ea1d670748f9c21af4f5d9e
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@90429b3dea365e9a1b0cb82d7f98aabf3089dc63
      - name: Check documentation
        env:
          RUSTDOCFLAGS: -D warnings
        uses: actions-rs/cargo@9e120dd99b0fbad1c065f686657e914e76bd7b72
        with:
          command: doc
          args: --no-deps --document-private-items --workspace --examples
          #@todo do websockets when we fix them

  publish-dry-run:
    name: Publish dry run
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@7d3610100de4da85ebb79cf22ad4c19bb1f68e12
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@f7003eed5ea1f2175ea1d670748f9c21af4f5d9e
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@90429b3dea365e9a1b0cb82d7f98aabf3089dc63
      - uses: actions-rs/cargo@9e120dd99b0fbad1c065f686657e914e76bd7b72
        with:
          command: publish
          args: --dry-run -p stratum-server

  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@7d3610100de4da85ebb79cf22ad4c19bb1f68e12
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@f7003eed5ea1f2175ea1d670748f9c21af4f5d9e
        with:
          toolchain: stable
          components: llvm-tools-preview
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@74efbe3ca41988b1c402800fbd3a72c98c9d8eaa
        with:
          tool: cargo-llvm-cov
      - uses: taiki-e/install-action@74efbe3ca41988b1c402800fbd3a72c98c9d8eaa
        with:
          tool: nextest
      - uses: Swatinem/rust-cache@v1
      - name: Generate code coverage
        run: |
          cargo llvm-cov clean --workspace
          cargo llvm-cov nextest --profile ci --no-report --features tcp
          cargo llvm-cov nextest --profile ci --no-report --features websockets
          cargo llvm-cov --no-run --lcov --output-path lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@7f20bd4c4151750a1d013be0901b7e35a46c2aad
        with:
          files: lcov.info
          fail_ci_if_error: true

  cargo_bloat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        uses: dtolnay/rust-toolchain@f7003eed5ea1f2175ea1d670748f9c21af4f5d9e
        with:
          toolchain: stable
      - name: Run cargo bloat
        uses: orf/cargo-bloat-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude_packages: "bench"

  ci-success:
    name: ci
    if: success()
    needs:
      - test-versions
      - msrv
      - tidy
      - docs
      - publish-dry-run
      - coverage
      - cargo_bloat
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@7d3610100de4da85ebb79cf22ad4c19bb1f68e12
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Mark the job as a success
        run: exit 0
